services:
  todo-app:
    image: node:20-alpine
    command: sh -c "yarn install && node app.js"
    ports:
      - 8080:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGO_URI: mongodb://mongoDB1:audition123@mongo:27017/todos
  mongo:
    image: mongo:6.0
    volumes:
      - todo-mongo-data:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoDB1
      MONGO_INITDB_ROOT_PASSWORD: audition123

volumes:
  todo-mongo-data:
